
import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.researchers': 'Researchers',
    'nav.about': 'About Us',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'hero.title': 'Connecting students with research experts',
    'hero.subtitle': 'Book one-on-one consultations with research experts across various fields. Get personalized guidance for your research projects.',
    'hero.findResearchers': 'Find Researchers',
    'hero.joinAsResearcher': 'Join as a Researcher',
    
    // How It Works translations
    'howItWorks.title': 'How ScholarConnect Works',
    'howItWorks.subtitle': 'Connect with expert researchers in just a few simple steps',
    'howItWorks.gettingStarted': 'Getting Started is Easy',
    'howItWorks.step1.title': '1. Search & Discover',
    'howItWorks.step1.description': 'Browse our extensive network of researchers by field, expertise, institution, or specific research interests.',
    'howItWorks.step2.title': '2. Book Consultation',
    'howItWorks.step2.description': 'Select your preferred researcher and book a consultation at a time that works for both of you.',
    'howItWorks.step3.title': '3. Connect & Learn',
    'howItWorks.step3.description': 'Meet virtually with your chosen expert and get personalized guidance for your research project.',
    
    'howItWorks.detailedWorkflow': 'Detailed Workflow',
    'howItWorks.workflow.registration.title': 'Registration & Profile Setup',
    'howItWorks.workflow.registration.description': 'Create your account and build a comprehensive profile to get matched with the right researchers.',
    'howItWorks.workflow.registration.step1': 'Sign up with email or institutional SSO',
    'howItWorks.workflow.registration.step2': 'Complete your academic profile with research interests',
    'howItWorks.workflow.registration.step3': 'Verify your email and set up payment methods',
    
    'howItWorks.workflow.search.title': 'Search & Filter Researchers',
    'howItWorks.workflow.search.description': 'Use our advanced search and filtering system to find researchers who match your specific needs.',
    'howItWorks.workflow.search.step1': 'Search by research field, keywords, or institution',
    'howItWorks.workflow.search.step2': 'Filter by availability, rating, and expertise level',
    'howItWorks.workflow.search.step3': 'Review profiles, publications, and student reviews',
    
    'howItWorks.workflow.booking.title': 'Booking & Scheduling',
    'howItWorks.workflow.booking.description': 'Book consultations that fit your schedule and research timeline.',
    'howItWorks.workflow.booking.step1': 'Select preferred date and time slots',
    'howItWorks.workflow.booking.step2': 'Specify your research challenges and goals',
    'howItWorks.workflow.booking.step3': 'Confirm booking and receive meeting details',
    
    'howItWorks.workflow.consultation.title': 'Consultation Session',
    'howItWorks.workflow.consultation.description': 'Engage in productive research discussions with your chosen expert.',
    'howItWorks.workflow.consultation.step1': 'Join the video call at the scheduled time',
    'howItWorks.workflow.consultation.step2': 'Discuss your research with the expert',
    'howItWorks.workflow.consultation.step3': 'Receive actionable advice and resources',
    
    'howItWorks.workflow.followUp.title': 'Follow-up & Review',
    'howItWorks.workflow.followUp.description': 'Complete the consultation cycle with feedback and continued support.',
    'howItWorks.workflow.followUp.step1': 'Receive session summary and recommendations',
    'howItWorks.workflow.followUp.step2': 'Rate and review your experience',
    'howItWorks.workflow.followUp.step3': 'Book follow-up sessions if needed',
    
    'howItWorks.platformFeatures': 'Platform Features',
    'howItWorks.features.guidance.title': 'Research Guidance',
    'howItWorks.features.guidance.description': 'Get expert help with research ideas, methodology, literature reviews, and thesis defense preparation.',
    'howItWorks.features.coAuthor.title': 'Co-Authoring Opportunities',
    'howItWorks.features.coAuthor.description': 'Collaborate with researchers on publications, from journal articles to conference papers.',
    'howItWorks.features.quality.title': 'Quality Assurance',
    'howItWorks.features.quality.description': 'All researchers are verified experts with proven track records in their respective fields.',
    'howItWorks.features.scheduling.title': 'Flexible Scheduling',
    'howItWorks.features.scheduling.description': 'Book sessions that fit your schedule, with options for one-time consultations or ongoing mentorship.',
    'howItWorks.features.communication.title': 'Secure Communication',
    'howItWorks.features.communication.description': 'Built-in messaging system and video conferencing for seamless researcher-student interaction.',
    'howItWorks.features.security.title': 'Data Security',
    'howItWorks.features.security.description': 'Your research data and personal information are protected with enterprise-grade security.',
    
    'howItWorks.forResearchers.title': 'For Researchers',
    'howItWorks.forResearchers.description': 'Share your expertise, build your reputation, and earn additional income by mentoring the next generation of researchers.',
    'howItWorks.stats.researchers': 'Active Researchers',
    'howItWorks.stats.students': 'Students Helped',
    'howItWorks.stats.satisfaction': 'Satisfaction Rate',
    'howItWorks.joinAsResearcher': 'Join as a Researcher',
    'howItWorks.cta.title': 'Ready to Get Started?',
    'howItWorks.cta.description': 'Join thousands of students who have already improved their research with expert guidance.',
    
    // Research Aides translations
    'researchAides.title': 'Research Aides',
    'researchAides.subtitle': 'Connect with specialized professionals for targeted research support',
    'researchAides.searchPlaceholder': 'Search by name, skills, or specialization...',
    'researchAides.categories.all': 'All Categories',
    'researchAides.categories.gis': 'GIS Specialists',
    'researchAides.categories.statistics': 'Statisticians',
    'researchAides.categories.cartography': 'Cartographers',
    'researchAides.categories.dataCollection': 'Data Collectors',
    'researchAides.categories.journalPublishing': 'Journal Publishing Aides',
    'researchAides.categories.academicEditing': 'Academic Editors',
    'researchAides.results.title': 'Available Research Aides',
    'researchAides.results.found': 'Found',
    'researchAides.results.specialists': 'specialists',
    'researchAides.card.skills': 'Skills',
    'researchAides.card.experience': 'experience',
    'researchAides.card.available': 'Available',
    'researchAides.card.busy': 'Busy',
    'researchAides.card.contact': 'Contact',
    'researchAides.noResults': 'No research aides found matching your criteria.',
    'researchAides.cta.title': 'Are you a research specialist?',
    'researchAides.cta.description': 'Join our platform and offer your specialized services to students and researchers.',
    'researchAides.cta.joinButton': 'Join as Research Aide',
    
    // Contact translations
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team for support, partnerships, or any questions',
    'contact.form.title': 'Send us a Message',
    'contact.form.firstName': 'First Name',
    'contact.form.firstNamePlaceholder': 'Enter your first name',
    'contact.form.lastName': 'Last Name',
    'contact.form.lastNamePlaceholder': 'Enter your last name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'What is this about?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'contact.form.send': 'Send Message',
    
    'contact.info.title': 'Contact Information',
    'contact.info.email.title': 'Email',
    'contact.info.email.general': 'info@scholarconnect.org',
    'contact.info.email.support': 'support@scholarconnect.org',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.main': '+237 6XX XXX XXX',
    'contact.info.phone.whatsapp': 'WhatsApp: +237 6XX XXX XXX',
    'contact.info.address.title': 'Address',
    'contact.info.address.street': 'University of Yaoundé I Campus',
    'contact.info.address.city': 'Yaoundé, Cameroon',
    'contact.info.hours.title': 'Office Hours',
    'contact.info.hours.weekdays': 'Monday - Friday: 8:00 AM - 6:00 PM',
    'contact.info.hours.weekends': 'Saturday: 9:00 AM - 2:00 PM',
    
    'contact.services.title': 'Special Services',
    'contact.services.partnership.title': 'Institutional Partnership',
    'contact.services.partnership.description': 'Partner with us to enhance your institution\'s research capabilities and student support services.',
    'contact.services.partnership.benefit1': 'Bulk access to expert researchers for your students',
    'contact.services.partnership.benefit2': 'Customized research mentorship programs',
    'contact.services.partnership.benefit3': 'Integration with your existing academic systems',
    'contact.services.partnership.benefit4': 'Discounted rates for institutional members',
    'contact.services.partnership.contact': 'Contact Partnership Team',
    
    'contact.services.financialAid.title': 'Financial Aid for Students',
    'contact.services.financialAid.description': 'We believe financial constraints shouldn\'t limit access to quality research guidance. Explore our aid programs.',
    'contact.services.financialAid.program1': 'Merit-based consultation scholarships',
    'contact.services.financialAid.program2': 'Need-based financial assistance',
    'contact.services.financialAid.program3': 'Work-study program participation',
    'contact.services.financialAid.program4': 'Partner institution discounts',
    'contact.services.financialAid.apply': 'Apply for Financial Aid',
    
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1.question': 'How quickly can I get a response to my inquiry?',
    'contact.faq.q1.answer': 'We typically respond to all inquiries within 24 hours during business days. For urgent matters, please call our direct line.',
    'contact.faq.q2.question': 'What types of institutional partnerships do you offer?',
    'contact.faq.q2.answer': 'We offer various partnership models including bulk licensing, white-label solutions, and custom integration with your existing academic platforms.',
    'contact.faq.q3.question': 'How do I apply for financial aid?',
    'contact.faq.q3.answer': 'Students can apply for financial aid through our online application form. You\'ll need to provide academic transcripts and financial documentation.',
    'contact.faq.q4.question': 'Can researchers from our institution join your platform?',
    'contact.faq.q4.answer': 'Yes! We welcome qualified researchers from all accredited institutions. They can apply through our researcher registration process.',
    
    // Booking translations
    'booking.title': 'Book a Consultation',
    'booking.selectDate': 'Select a Date:',
    'booking.selectTime': 'Select a Time:',
    'booking.challenge': "What's your challenge? (Select all that apply)",
    'booking.comment': 'Leave a comment:',
    'booking.fee': 'Consultation Fee:',
    'booking.complete': 'Complete Booking',
    'challenge.generateIdea': 'Generate a research idea',
    'challenge.proposalWriting': 'Proposal writing',
    'challenge.literatureReview': 'Literature review',
    'challenge.frameworks': 'Conceptual and theoretical frameworks',
    'challenge.methodology': 'Methodology',
    'challenge.reportWriting': 'Report writing',
    'challenge.documentReview': 'Live document review',
    'challenge.guidance': 'General research guidance',
    'challenge.coAuthor': 'Co-author an article',
    'challenge.expertKnowledge': 'Expert knowledge',
    'challenge.interview': 'Interview a researcher',
    'challenge.mediaVisibility': 'Media visibility',
    'about.title': 'About ScholarConnect',
    'about.subtitle': 'Bridging the gap in research guidance to elevate research quality, mentorship, and academic excellence',
    'about.whoWeAre': 'Who We Are',
    'about.description': 'ScholarConnect is a digital platform where researchers, students, and lecturers connect for paid, flexible research and thesis defense consultations.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To become Africa\'s leading academic support platform, empowering every student to conduct impactful research, access expert mentorship, and confidently defend their work in a digitally inclusive environment.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To provide a full-spectrum academic ecosystem that connects students with expert researchers to elevate research quality, mentorship, and academic excellence across the continent.',
    'about.valueProposition': 'Value Proposition',
    'about.valuePropositionText': 'Empowering students to move from research ideation to confident project defense while enabling institutions to digitise and standardise mentorship and evaluation.',
    'about.coreValues': 'Our Core Values',
    'about.access': 'Access',
    'about.accessText': 'We believe every student, regardless of background or location, deserves access to quality academic support.',
    'about.integrity': 'Integrity',
    'about.integrityText': 'We promote honest, ethical academic collaboration and mentorship, upholding academic integrity at every level.',
    'about.excellence': 'Excellence',
    'about.excellenceText': 'We are committed to raising the standard of research and defense across Africa\'s higher education systems.',
    'about.innovation': 'Innovation',
    'about.innovationText': 'We use cutting-edge technology, including AI, to reimagine how students learn, research, and defend their ideas.',
    'about.collaboration': 'Collaboration',
    'about.collaborationText': 'We foster strong partnerships between students, lecturers, and institutions to enhance academic and societal outcomes.',
    'about.empowerment': 'Empowerment',
    'about.empowermentText': 'We empower students to grow intellectually and professionally by building confidence in their research capabilities.'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.researchers': 'Chercheurs',
    'nav.about': 'À propos',
    'nav.login': 'Connexion',
    'nav.register': "S'inscrire",
    'hero.title': 'Connecter les étudiants avec des experts en recherche',
    'hero.subtitle': 'Réservez des consultations individuelles avec des experts en recherche dans divers domaines. Obtenez des conseils personnalisés pour vos projets de recherche.',
    'hero.findResearchers': 'Trouver des chercheurs',
    'hero.joinAsResearcher': 'Rejoindre en tant que chercheur',
    
    // How It Works translations in French
    'howItWorks.title': 'Comment fonctionne ScholarConnect',
    'howItWorks.subtitle': 'Connectez-vous avec des chercheurs experts en quelques étapes simples',
    'howItWorks.gettingStarted': 'Commencer est facile',
    'howItWorks.step1.title': '1. Rechercher et découvrir',
    'howItWorks.step1.description': 'Parcourez notre vaste réseau de chercheurs par domaine, expertise, institution ou intérêts de recherche spécifiques.',
    'howItWorks.step2.title': '2. Réserver une consultation',
    'howItWorks.step2.description': 'Sélectionnez votre chercheur préféré et réservez une consultation à un moment qui vous convient.',
    'howItWorks.step3.title': '3. Se connecter et apprendre',
    'howItWorks.step3.description': 'Rencontrez virtuellement votre expert choisi et obtenez des conseils personnalisés pour votre projet de recherche.',
    
    'howItWorks.detailedWorkflow': 'Flux de travail détaillé',
    'howItWorks.workflow.registration.title': 'Inscription et configuration du profil',
    'howItWorks.workflow.registration.description': 'Créez votre compte et construisez un profil complet pour être mis en relation avec les bons chercheurs.',
    'howItWorks.workflow.registration.step1': 'Inscrivez-vous par email ou SSO institutionnel',
    'howItWorks.workflow.registration.step2': 'Complétez votre profil académique avec vos intérêts de recherche',
    'howItWorks.workflow.registration.step3': 'Vérifiez votre email et configurez les méthodes de paiement',
    
    'howItWorks.workflow.search.title': 'Rechercher et filtrer les chercheurs',
    'howItWorks.workflow.search.description': 'Utilisez notre système de recherche et de filtrage avancé pour trouver des chercheurs qui correspondent à vos besoins spécifiques.',
    'howItWorks.workflow.search.step1': 'Rechercher par domaine de recherche, mots-clés ou institution',
    'howItWorks.workflow.search.step2': 'Filtrer par disponibilité, évaluation et niveau d\'expertise',
    'howItWorks.workflow.search.step3': 'Examiner les profils, publications et avis d\'étudiants',
    
    'howItWorks.workflow.booking.title': 'Réservation et planification',
    'howItWorks.workflow.booking.description': 'Réservez des consultations qui s\'adaptent à votre emploi du temps et à votre calendrier de recherche.',
    'howItWorks.workflow.booking.step1': 'Sélectionnez les créneaux de date et heure préférés',
    'howItWorks.workflow.booking.step2': 'Spécifiez vos défis et objectifs de recherche',
    'howItWorks.workflow.booking.step3': 'Confirmez la réservation et recevez les détails de la réunion',
    
    'howItWorks.workflow.consultation.title': 'Session de consultation',
    'howItWorks.workflow.consultation.description': 'Engagez-vous dans des discussions de recherche productives avec votre expert choisi.',
    'howItWorks.workflow.consultation.step1': 'Rejoignez l\'appel vidéo à l\'heure prévue',
    'howItWorks.workflow.consultation.step2': 'Discutez de votre recherche avec l\'expert',
    'howItWorks.workflow.consultation.step3': 'Recevez des conseils actionnables et des ressources',
    
    'howItWorks.workflow.followUp.title': 'Suivi et évaluation',
    'howItWorks.workflow.followUp.description': 'Complétez le cycle de consultation avec des commentaires et un soutien continu.',
    'howItWorks.workflow.followUp.step1': 'Recevez le résumé de session et les recommandations',
    'howItWorks.workflow.followUp.step2': 'Évaluez et commentez votre expérience',
    'howItWorks.workflow.followUp.step3': 'Réservez des sessions de suivi si nécessaire',
    
    'howItWorks.platformFeatures': 'Fonctionnalités de la plateforme',
    'howItWorks.features.guidance.title': 'Orientation de recherche',
    'howItWorks.features.guidance.description': 'Obtenez de l\'aide d\'experts avec les idées de recherche, la méthodologie, les revues de littérature et la préparation de soutenance de thèse.',
    'howItWorks.features.coAuthor.title': 'Opportunités de co-écriture',
    'howItWorks.features.coAuthor.description': 'Collaborez avec des chercheurs sur des publications, des articles de journaux aux articles de conférence.',
    'howItWorks.features.quality.title': 'Assurance qualité',
    'howItWorks.features.quality.description': 'Tous les chercheurs sont des experts vérifiés avec des antécédents prouvés dans leurs domaines respectifs.',
    'howItWorks.features.scheduling.title': 'Planification flexible',
    'howItWorks.features.scheduling.description': 'Réservez des sessions qui s\'adaptent à votre emploi du temps, avec des options pour des consultations ponctuelles ou un mentorat continu.',
    'howItWorks.features.communication.title': 'Communication sécurisée',
    'howItWorks.features.communication.description': 'Système de messagerie intégré et vidéoconférence pour une interaction transparente chercheur-étudiant.',
    'howItWorks.features.security.title': 'Sécurité des données',
    'howItWorks.features.security.description': 'Vos données de recherche et informations personnelles sont protégées avec une sécurité de niveau entreprise.',
    
    'howItWorks.forResearchers.title': 'Pour les chercheurs',
    'howItWorks.forResearchers.description': 'Partagez votre expertise, construisez votre réputation et gagnez un revenu supplémentaire en encadrant la prochaine génération de chercheurs.',
    'howItWorks.stats.researchers': 'Chercheurs actifs',
    'howItWorks.stats.students': 'Étudiants aidés',
    'howItWorks.stats.satisfaction': 'Taux de satisfaction',
    'howItWorks.joinAsResearcher': 'Rejoindre en tant que chercheur',
    'howItWorks.cta.title': 'Prêt à commencer?',
    'howItWorks.cta.description': 'Rejoignez des milliers d\'étudiants qui ont déjà amélioré leur recherche avec des conseils d\'experts.',
    
    // Research Aides translations in French
    'researchAides.title': 'Aides à la recherche',
    'researchAides.subtitle': 'Connectez-vous avec des professionnels spécialisés pour un soutien de recherche ciblé',
    'researchAides.searchPlaceholder': 'Rechercher par nom, compétences ou spécialisation...',
    'researchAides.categories.all': 'Toutes les catégories',
    'researchAides.categories.gis': 'Spécialistes SIG',
    'researchAides.categories.statistics': 'Statisticiens',
    'researchAides.categories.cartography': 'Cartographes',
    'researchAides.categories.dataCollection': 'Collecteurs de données',
    'researchAides.categories.journalPublishing': 'Aides à la publication de journaux',
    'researchAides.categories.academicEditing': 'Éditeurs académiques',
    'researchAides.results.title': 'Aides à la recherche disponibles',
    'researchAides.results.found': 'Trouvé',
    'researchAides.results.specialists': 'spécialistes',
    'researchAides.card.skills': 'Compétences',
    'researchAides.card.experience': 'expérience',
    'researchAides.card.available': 'Disponible',
    'researchAides.card.busy': 'Occupé',
    'researchAides.card.contact': 'Contacter',
    'researchAides.noResults': 'Aucune aide à la recherche trouvée correspondant à vos critères.',
    'researchAides.cta.title': 'Êtes-vous un spécialiste de la recherche?',
    'researchAides.cta.description': 'Rejoignez notre plateforme et offrez vos services spécialisés aux étudiants et chercheurs.',
    'researchAides.cta.joinButton': 'Rejoindre en tant qu\'aide à la recherche',
    
    // Contact translations in French
    'contact.title': 'Nous contacter',
    'contact.subtitle': 'Contactez notre équipe pour le support, les partenariats ou toute question',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.firstName': 'Prénom',
    'contact.form.firstNamePlaceholder': 'Entrez votre prénom',
    'contact.form.lastName': 'Nom',
    'contact.form.lastNamePlaceholder': 'Entrez votre nom',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Entrez votre adresse email',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'De quoi s\'agit-il?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Dites-nous comment nous pouvons vous aider...',
    'contact.form.send': 'Envoyer le message',
    
    'contact.info.title': 'Informations de contact',
    'contact.info.email.title': 'Email',
    'contact.info.email.general': 'info@scholarconnect.org',
    'contact.info.email.support': 'support@scholarconnect.org',
    'contact.info.phone.title': 'Téléphone',
    'contact.info.phone.main': '+237 6XX XXX XXX',
    'contact.info.phone.whatsapp': 'WhatsApp: +237 6XX XXX XXX',
    'contact.info.address.title': 'Adresse',
    'contact.info.address.street': 'Campus Université de Yaoundé I',
    'contact.info.address.city': 'Yaoundé, Cameroun',
    'contact.info.hours.title': 'Heures de bureau',
    'contact.info.hours.weekdays': 'Lundi - Vendredi: 8h00 - 18h00',
    'contact.info.hours.weekends': 'Samedi: 9h00 - 14h00',
    
    'contact.services.title': 'Services spéciaux',
    'contact.services.partnership.title': 'Partenariat institutionnel',
    'contact.services.partnership.description': 'Partenariez avec nous pour améliorer les capacités de recherche de votre institution et les services de soutien aux étudiants.',
    'contact.services.partnership.benefit1': 'Accès en masse aux chercheurs experts pour vos étudiants',
    'contact.services.partnership.benefit2': 'Programmes de mentorat de recherche personnalisés',
    'contact.services.partnership.benefit3': 'Intégration avec vos systèmes académiques existants',
    'contact.services.partnership.benefit4': 'Tarifs réduits pour les membres institutionnels',
    'contact.services.partnership.contact': 'Contacter l\'équipe partenariat',
    
    'contact.services.financialAid.title': 'Aide financière pour les étudiants',
    'contact.services.financialAid.description': 'Nous croyons que les contraintes financières ne devraient pas limiter l\'accès à des conseils de recherche de qualité. Explorez nos programmes d\'aide.',
    'contact.services.financialAid.program1': 'Bourses de consultation basées sur le mérite',
    'contact.services.financialAid.program2': 'Assistance financière basée sur les besoins',
    'contact.services.financialAid.program3': 'Participation au programme travail-études',
    'contact.services.financialAid.program4': 'Remises pour les institutions partenaires',
    'contact.services.financialAid.apply': 'Demander une aide financière',
    
    'contact.faq.title': 'Questions fréquemment posées',
    'contact.faq.q1.question': 'À quelle vitesse puis-je obtenir une réponse à ma demande?',
    'contact.faq.q1.answer': 'Nous répondons généralement à toutes les demandes dans les 24 heures pendant les jours ouvrables. Pour les questions urgentes, veuillez appeler notre ligne directe.',
    'contact.faq.q2.question': 'Quels types de partenariats institutionnels offrez-vous?',
    'contact.faq.q2.answer': 'Nous offrons divers modèles de partenariat incluant la licence en vrac, les solutions en marque blanche et l\'intégration personnalisée avec vos plateformes académiques existantes.',
    'contact.faq.q3.question': 'Comment puis-je demander une aide financière?',
    'contact.faq.q3.answer': 'Les étudiants peuvent demander une aide financière à travers notre formulaire de demande en ligne. Vous devrez fournir des relevés académiques et une documentation financière.',
    'contact.faq.q4.question': 'Les chercheurs de notre institution peuvent-ils rejoindre votre plateforme?',
    'contact.faq.q4.answer': 'Oui! Nous accueillons les chercheurs qualifiés de toutes les institutions accréditées. Ils peuvent postuler à travers notre processus d\'inscription de chercheur.',
    
    // Booking translations in French
    'booking.title': 'Réserver une consultation',
    'booking.selectDate': 'Sélectionnez une date :',
    'booking.selectTime': 'Sélectionnez une heure :',
    'booking.challenge': 'Quel est votre défi ? (Sélectionnez tous ceux qui s\'appliquent)',
    'booking.comment': 'Laissez un commentaire :',
    'booking.fee': 'Frais de consultation :',
    'booking.complete': 'Finaliser la réservation',
    'challenge.generateIdea': 'Générer une idée de recherche',
    'challenge.proposalWriting': 'Rédaction de proposition',
    'challenge.literatureReview': 'Revue de littérature',
    'challenge.frameworks': 'Cadres conceptuels et théoriques',
    'challenge.methodology': 'Méthodologie',
    'challenge.reportWriting': 'Rédaction de rapport',
    'challenge.documentReview': 'Révision de document en direct',
    'challenge.guidance': 'Conseils généraux de recherche',
    'challenge.coAuthor': 'Co-auteur d\'un article',
    'challenge.expertKnowledge': 'Connaissances d\'expert',
    'challenge.interview': 'Interviewer un chercheur',
    'challenge.mediaVisibility': 'Visibilité médiatique',
    'about.title': 'À propos de ScholarConnect',
    'about.subtitle': 'Combler le fossé dans l\'orientation de la recherche pour élever la qualité de la recherche, le mentorat et l\'excellence académique',
    'about.whoWeAre': 'Qui nous sommes',
    'about.description': 'ScholarConnect est une plateforme numérique où les chercheurs, étudiants et enseignants se connectent pour des consultations payées et flexibles de recherche et de soutenance de thèse.',
    'about.vision': 'Notre Vision',
    'about.visionText': 'Devenir la principale plateforme de soutien académique en Afrique, permettant à chaque étudiant de mener des recherches d\'impact, d\'accéder au mentorat d\'experts et de défendre son travail avec confiance dans un environnement numérique inclusif.',
    'about.mission': 'Notre Mission',
    'about.missionText': 'Fournir un écosystème académique complet qui connecte les étudiants avec des chercheurs experts pour élever la qualité de la recherche, le mentorat et l\'excellence académique à travers le continent.',
    'about.valueProposition': 'Proposition de valeur',
    'about.valuePropositionText': 'Permettre aux étudiants de passer de l\'idéation de recherche à la défense confiante de projet tout en permettant aux institutions de numériser et de standardiser le mentorat et l\'évaluation.',
    'about.coreValues': 'Nos valeurs fondamentales',
    'about.access': 'Accès',
    'about.accessText': 'Nous croyons que chaque étudiant, indépendamment de son origine ou de sa localisation, mérite l\'accès à un soutien académique de qualité.',
    'about.integrity': 'Intégrité',
    'about.integrityText': 'Nous promouvons une collaboration académique et un mentorat honnêtes et éthiques, maintenant l\'intégrité académique à tous les niveaux.',
    'about.excellence': 'Excellence',
    'about.excellenceText': 'Nous nous engageons à élever le standard de recherche et de défense dans les systèmes d\'enseignement supérieur africains.',
    'about.innovation': 'Innovation',
    'about.innovationText': 'Nous utilisons une technologie de pointe, y compris l\'IA, pour réinventer la façon dont les étudiants apprennent, recherchent et défendent leurs idées.',
    'about.collaboration': 'Collaboration',
    'about.collaborationText': 'Nous favorisons des partenariats solides entre étudiants, enseignants et institutions pour améliorer les résultats académiques et sociétaux.',
    'about.empowerment': 'Autonomisation',
    'about.empowermentText': 'Nous autonomisons les étudiants à croître intellectuellement et professionnellement en renforçant la confiance en leurs capacités de recherche.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
