// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aigusgidjcfkhcmsghmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZ3VzZ2lkamNma2hjbXNnaG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTUzNzEsImV4cCI6MjA2Mzc3MTM3MX0.c9eQqGnSbMdtAZLi_jwvZezv7ZZhYb9rlC9-7cup1b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);