// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yujuomiqwydnwovgwtrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1anVvbWlxd3lkbndvdmd3dHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTgxMDcsImV4cCI6MjA3MDA5NDEwN30._sfS9ndN3poquQyzjyIsnHIK4jFGyf1wwX8gCXBW68I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);